version:  0.1

payment:
  best-model-payment-amount: 0.03

ml:
  dataset:
    sha256: 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3'
    format: CSV
    training-set-size: 0.7
    test-set-size: 0.3
    source:
      features: 'tests/data/abalone.csv'
      labels: 'tests/data/abalone.csv'


  validation:
    strategy:
      method: Holdout
      size: 0.1

  optimizer:
    type:  SGD
    optimizer_initialization_parameters:
      learning_rate: 0.1
      momentum: 0.0
    tau: 12.0
    epochs: 30
    batch-size: 100
    initializer:
      name: Xavier
      parameters:
        magnitude: 2.24

  model:
    type: FC-DNN
    layers:
      - id: 'layer1'
        type: Dense
        nodes: 128
        activation: relu
      - id: 'layer2'
        type: Dense
        nodes: 64
        activation: relu
      - id: 'output'
        type: Dense
        nodes: 10
    loss: SoftmaxCrossEntropyLoss

  evaluation-metrics:
    - Accuracy
    - CrossEntropy
