version:  0.1

payment:
  best-model-payment-amount: 0.03

ml:
  dataset:
    sha256: 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3'
    format: MNIST
    training-set-size: 0.85714285715
    test-set-size: 0.14285714286
    source: 
      features: 'http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz'
      labels: 'http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz'

  validation:
    strategy: 
      method: Holdout
      size: 0.1

  optimizer:
    type:  SGD
    optimizer_initialization_parameters:
      learning_rate: 1e-3
      momentum: 0.0
    tau: 12.0
    epochs: 30
    batch-size: 100
    initializer:
      name: Xavier
      parameters:
        magnitude: 2.24

  model:
    type: FC-DNN
    layers:
      - name: 'dense_1'
        type: Dense
        units: 64
        activation: relu
      - name: 'dense_2'
        type: Dense
        units: 64
        activation: relu
    loss: SoftmaxCrossEntropyLoss

  evaluation-metrics:
    - Accuracy
    - CrossEntropy
