# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import task_info_pb2 as task__info__pb2


class TaskInfoStub(object):
    """definition of verifier service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWaitingTasks = channel.unary_unary(
                '/pai.pouw.task_info.TaskInfo/GetWaitingTasks',
                request_serializer=task__info__pb2.TaskListRequest.SerializeToString,
                response_deserializer=task__info__pb2.TaskListResponse.FromString,
                )


class TaskInfoServicer(object):
    """definition of verifier service
    """

    def GetWaitingTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWaitingTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaitingTasks,
                    request_deserializer=task__info__pb2.TaskListRequest.FromString,
                    response_serializer=task__info__pb2.TaskListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pai.pouw.task_info.TaskInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskInfo(object):
    """definition of verifier service
    """

    @staticmethod
    def GetWaitingTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pai.pouw.task_info.TaskInfo/GetWaitingTasks',
            task__info__pb2.TaskListRequest.SerializeToString,
            task__info__pb2.TaskListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
