# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task_info.proto',
  package='pai.pouw.task_info',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftask_info.proto\x12\x12pai.pouw.task_info\"\x11\n\x0fTaskListRequest\"!\n\x10TaskListResponse\x12\r\n\x05tasks\x18\x01 \x03(\t2j\n\x08TaskInfo\x12^\n\x0fGetWaitingTasks\x12#.pai.pouw.task_info.TaskListRequest\x1a$.pai.pouw.task_info.TaskListResponse\"\x00\x62\x06proto3'
)




_TASKLISTREQUEST = _descriptor.Descriptor(
  name='TaskListRequest',
  full_name='pai.pouw.task_info.TaskListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=56,
)


_TASKLISTRESPONSE = _descriptor.Descriptor(
  name='TaskListResponse',
  full_name='pai.pouw.task_info.TaskListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='pai.pouw.task_info.TaskListResponse.tasks', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['TaskListRequest'] = _TASKLISTREQUEST
DESCRIPTOR.message_types_by_name['TaskListResponse'] = _TASKLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskListRequest = _reflection.GeneratedProtocolMessageType('TaskListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTREQUEST,
  '__module__' : 'task_info_pb2'
  # @@protoc_insertion_point(class_scope:pai.pouw.task_info.TaskListRequest)
  })
_sym_db.RegisterMessage(TaskListRequest)

TaskListResponse = _reflection.GeneratedProtocolMessageType('TaskListResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTRESPONSE,
  '__module__' : 'task_info_pb2'
  # @@protoc_insertion_point(class_scope:pai.pouw.task_info.TaskListResponse)
  })
_sym_db.RegisterMessage(TaskListResponse)



_TASKINFO = _descriptor.ServiceDescriptor(
  name='TaskInfo',
  full_name='pai.pouw.task_info.TaskInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWaitingTasks',
    full_name='pai.pouw.task_info.TaskInfo.GetWaitingTasks',
    index=0,
    containing_service=None,
    input_type=_TASKLISTREQUEST,
    output_type=_TASKLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKINFO)

DESCRIPTOR.services_by_name['TaskInfo'] = _TASKINFO

# @@protoc_insertion_point(module_scope)
