# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import task_info_pb2 as task__info__pb2


class TaskInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWaitingTasks = channel.unary_unary(
                '/pai.pouw.task_info.TaskInfo/GetWaitingTasks',
                request_serializer=task__info__pb2.TaskListRequest.SerializeToString,
                response_deserializer=task__info__pb2.TaskListResponse.FromString,
                )
        self.GetStartedTasks = channel.unary_unary(
                '/pai.pouw.task_info.TaskInfo/GetStartedTasks',
                request_serializer=task__info__pb2.TaskListRequest.SerializeToString,
                response_deserializer=task__info__pb2.TaskListResponse.FromString,
                )
        self.GetCompletedTasks = channel.unary_unary(
                '/pai.pouw.task_info.TaskInfo/GetCompletedTasks',
                request_serializer=task__info__pb2.TaskListRequest.SerializeToString,
                response_deserializer=task__info__pb2.TaskListResponse.FromString,
                )
        self.GetTaskDetails = channel.unary_unary(
                '/pai.pouw.task_info.TaskInfo/GetTaskDetails',
                request_serializer=task__info__pb2.TaskDetailsRequest.SerializeToString,
                response_deserializer=task__info__pb2.TaskDetailsResponse.FromString,
                )
        self.GetTaskID = channel.unary_unary(
                '/pai.pouw.task_info.TaskInfo/GetTaskID',
                request_serializer=task__info__pb2.TaskIDRequest.SerializeToString,
                response_deserializer=task__info__pb2.TaskIDResponse.FromString,
                )


class TaskInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWaitingTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStartedTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompletedTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWaitingTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaitingTasks,
                    request_deserializer=task__info__pb2.TaskListRequest.FromString,
                    response_serializer=task__info__pb2.TaskListResponse.SerializeToString,
            ),
            'GetStartedTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStartedTasks,
                    request_deserializer=task__info__pb2.TaskListRequest.FromString,
                    response_serializer=task__info__pb2.TaskListResponse.SerializeToString,
            ),
            'GetCompletedTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompletedTasks,
                    request_deserializer=task__info__pb2.TaskListRequest.FromString,
                    response_serializer=task__info__pb2.TaskListResponse.SerializeToString,
            ),
            'GetTaskDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskDetails,
                    request_deserializer=task__info__pb2.TaskDetailsRequest.FromString,
                    response_serializer=task__info__pb2.TaskDetailsResponse.SerializeToString,
            ),
            'GetTaskID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskID,
                    request_deserializer=task__info__pb2.TaskIDRequest.FromString,
                    response_serializer=task__info__pb2.TaskIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pai.pouw.task_info.TaskInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWaitingTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pai.pouw.task_info.TaskInfo/GetWaitingTasks',
            task__info__pb2.TaskListRequest.SerializeToString,
            task__info__pb2.TaskListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStartedTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pai.pouw.task_info.TaskInfo/GetStartedTasks',
            task__info__pb2.TaskListRequest.SerializeToString,
            task__info__pb2.TaskListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCompletedTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pai.pouw.task_info.TaskInfo/GetCompletedTasks',
            task__info__pb2.TaskListRequest.SerializeToString,
            task__info__pb2.TaskListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pai.pouw.task_info.TaskInfo/GetTaskDetails',
            task__info__pb2.TaskDetailsRequest.SerializeToString,
            task__info__pb2.TaskDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pai.pouw.task_info.TaskInfo/GetTaskID',
            task__info__pb2.TaskIDRequest.SerializeToString,
            task__info__pb2.TaskIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
