# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import verifier_pb2 as verifier__pb2


class VerifierStub(object):
  """definition of verifier service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Verify = channel.unary_unary(
        '/pai.pouw.verification.Verifier/Verify',
        request_serializer=verifier__pb2.Request.SerializeToString,
        response_deserializer=verifier__pb2.Response.FromString,
        )


class VerifierServicer(object):
  """definition of verifier service
  """

  def Verify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VerifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Verify': grpc.unary_unary_rpc_method_handler(
          servicer.Verify,
          request_deserializer=verifier__pb2.Request.FromString,
          response_serializer=verifier__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pai.pouw.verification.Verifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
